// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9wNIJx_OrrR9wf9Kd-nSmMw8ycioJi_U',
    appId: '1:332080945965:web:2e537d2f053855a15791a4',
    messagingSenderId: '332080945965',
    projectId: 'handplaydemo',
    authDomain: 'handplaydemo.firebaseapp.com',
    storageBucket: 'handplaydemo.firebasestorage.app',
    measurementId: 'G-25X7MNP3YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2PbLngEYQf5X3LS4CuHltS54AFGJ5r8',
    appId: '1:332080945965:android:85c1bf78bb55bd0c5791a4',
    messagingSenderId: '332080945965',
    projectId: 'handplaydemo',
    storageBucket: 'handplaydemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwF2WgW9pw60vbm_plw4bJIGzjw--okXg',
    appId: '1:332080945965:ios:c1015aaca898e08d5791a4',
    messagingSenderId: '332080945965',
    projectId: 'handplaydemo',
    storageBucket: 'handplaydemo.firebasestorage.app',
    iosClientId: '332080945965-509tilacqi8os4obrp22nnv3a6rr6n9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.handplayDemo',
  );
}
